include:
  - template: Security/SAST.gitlab-ci.yml
  
  # # GitLab Ultimate Only
  - template: DAST.gitlab-ci.yml
  



stages: 
  - build
  - test
  - verify
  - dast
  - deploy





# container_scanning:
#   variables:
#     DOCKER_IMAGE: $CI_REGISTRY_IMAGE:latest
#     CLAIR_TRACE: "true"


  


dast:
  # Register the user first, note this assumes the application is up and running for registration to succeed
  before_script: 
    - curl -v -d 'userName=$GOAT_USERNAME&firstName=test&lastName=test&password=$GOAT_PASSWORD&verify=$GOAT_PASSWORD&email=&_csrf=' "http://nodegoat:4000/signup"





deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://prod.example.com
  when: manual
  
